### ISSUE TITLE
Problems making the java example work

### ISSUE THREAD

**Issue by jhahkala** [atos-ari-aeon/fiware-cloud-messaging-sdk#2]
Hi,

I have the docker version of the platform running, but I can't make the java examples work.
The communication seems to work, I get subscription answer:
subscription received {"subkey":"testc-36040093-queu","ip":"xxx.xxx.xxx.xxx:3000","id":"tesetid","_id":"56ae6faf76a8f12b01000003","desc":"testiddesc"}

And on the server side I see the subscription message and the publish messages.
rest      | GET /subscribe/config 200 23ms - 116
rest      | GET /subscribe/218ca50e-4f39-4e6d-8ffc-91bdfb3cd550?id=tesetid&desc=testiddesc 200 19ms - 229
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 61ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 46ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 48ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 45ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 52ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 48ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 48ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 45ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 45ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 46ms - 82
rest      | POST /publish/9073b206-5eea-4b91-b726-4e2bba10f7b5 200 48ms - 83

But the client doesn't receive anything.

There is an error message after the second message that the receiver is taking a break:
an Error occured
io.socket.SocketIOException: Error while handshaking
    at io.socket.IOConnection.handshake(IOConnection.java:322)
    at io.socket.IOConnection.access$600(IOConnection.java:39)
    at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at io.socket.IOConnection.handshake(IOConnection.java:313)
    ... 2 more

I guess that could be the reason?

**Comment by jhahkala** [comment]
Forgot to mention that the receiver continues to run and the timeout doesn't really make sense as the communication to the server seems to work.

**Comment by atos-ari-aeon** [comment]
Hi Joni,

I guess the links to the SDKs are also wrong. Please, try to use the v0.2.1 of the Java SDK located here: http://gitlab.atosresearch.eu/ari/aeon-sdk/tree/master/SDK/releases/java

Let me know if you have further problems.

**Comment by atos-ari-aeon** [comment]
BTW, we are part of the fiware catalogue for a few months and we would like to know what are you using the Cloud Messaging GE for (if possible ;) 
All the comments you may have, please, let us know.

**Comment by jhahkala** [comment]
Is the sdk on the link you listed different from the sdk you get when cloning this repo?

We are trying to use this to give mobile users notifications about new files appearing to their system etc.

**Comment by atos-ari-aeon** [comment]
The one that I provided is v0.2.1 and the one you have is 0.2.0. Also the socket.io library is different. Regarding the usage of the SDK in mobile apps, you may have a lack of performance in your mobiles since it is not optimized to be used in Android. This is something that we are thinking about...

**Comment by jhahkala** [comment]
With the new jars and the example from here, in github with our settings, the behaviour is the same as before. It would be nice to see the new version of code here.

As for the performance, at the peak there would only be like a message per minute on the phone, that shouldn't be a problem?

**Comment by jhahkala** [comment]
Debugging the example and the sdk, found out that the client was talking also to the port 7789, which wasn't open. It would be good to list what ports and services should be open in the examples/playing pages...
